TL: Chap 2
TeamConfiture/SuNoFes pull request #112
Opened 2022-08-19 00:05 UTC by Lushion

premier jet chapitre 2

2022-08-19 10:22 UTC, KimiNako commented on game/tl/english/chap/chap1.rpy
> +    violet "Have you find it?"
found ?

2022-08-19 10:22 UTC, KimiNako commented on game/tl/english/chap/chap1.rpy
> +    "The guards rushes through the Garden of Violets. With Blanche out of sight, they vanish in a tiny back alley."
The guards rush through.../The Guard rushes through...

After losing sight of Blanche

2022-08-19 10:22 UTC, KimiNako commented on game/tl/english/chap/chap1.rpy
> +    "I will pick one for Daddy."
blanche "I will pick one for Daddy."

2022-08-19 10:22 UTC, KimiNako commented on game/tl/english/chap/chap1.rpy
> +    violet "Indeed. I am the Guardian of Purple"
il manque un point en fr et en

2022-08-19 10:22 UTC, KimiNako commented on game/tl/english/chap/chap1.rpy
> +    violet "A Guardian of Colors, you say? There are only seven of Guardian of Colors, and all of them are cats."
seven Guardian of Colors ?

2022-08-19 10:22 UTC, KimiNako commented on game/tl/english/chap/chap1.rpy
> +    violet "And… Lady Raindow will scold me…"
"And Lady Rainbow will scold me"

Rainbow et pas Raindow

2022-08-19 10:22 UTC, KimiNako commented on game/tl/english/chap/chap1.rpy
> +    violet "Oh nooooooooooo, not these eyes. They are too powerful."
cute ?

2022-08-19 10:22 UTC, KimiNako commented on game/tl/english/chap/chap1.rpy
> +    violet ""
"Indeed!"

2022-08-19 10:22 UTC, KimiNako commented on game/tl/english/screens.rpy
> +    new "Director, UI Designer et Developer"
"et" am I a joke to you?

2022-08-19 10:22 UTC, KimiNako commented on game/tl/english/screens.rpy
> +    new "Developer et sprite artist"
"et" am I a joke to you?

2022-08-19 10:22 UTC, KimiNako commented on game/tl/english/screens.rpy
> +    new "Developer et scenarist"
"et" am I a joke to you?

2022-08-19 10:23 UTC, KimiNako commented on game/tl/english/chap/chap1.rpy
> +    violet "Have you find it?"
found

2022-08-19 14:58 UTC, KimiNako commented on game/tl/english/chap/chap2.rpy
> +    indigo "If only I could learn their names… I would be able to describe the sky before me and to transmit this incredible knowledge to future travelers that will stop by my lake"
"before me" à enlever ?

transmit this incredible knowledge  => pass on

2022-08-19 14:58 UTC, KimiNako commented on game/tl/english/chap/chap2.rpy
> +    blanche "Ah! Wait, what are those"
où qu'il est le "?"

2022-08-19 16:25 UTC, Ayowel requested changes

2022-08-19 16:25 UTC, Ayowel commented on game/tl/english/chap/chap2.rpy
> +    blanche "I am sorry, I have never seen any thorn in my life."
`I'm sorry` ?

2022-08-19 16:25 UTC, Ayowel commented on game/tl/english/chap/chap2.rpy
> +    indigo "No talking back, it is customary to leave this lake having learn a thing or two. Look over there. These are reeds! You can see a swan in front of it and right there, these are duck, do yo
`having learned`
`these are ducks`

2022-08-19 16:25 UTC, Ayowel commented on game/tl/english/chap/chap2.rpy
> +    indigo "Really? If you did not come here to witness the beauty of the landscape, then what are you after?! Know that none crossed my path with any other objective!"
`no one crossed`, on est sur des vivants

2022-08-19 16:25 UTC, Ayowel commented on game/tl/english/chap/chap2.rpy
> +    # blanche "Il me faut absolument cette boule. Il en va de la vie de mon père ! Je veux lui montrer à quoi ressemble les couleurs de l'Arc-en-Ciel !"
`ressemblent`

2022-08-19 16:25 UTC, Ayowel commented on game/tl/english/chap/chap2.rpy
> +    indigo "I make exceptions only for those who prove their intellectual worth. Not for anyone. If you want this ball, then show me what your worth!"
`what your worth is` or `what you are worth`

2022-08-19 16:25 UTC, Ayowel commented on game/tl/english/chap/chap2.rpy
> +    blanche "You speak of the stars that form constellations"
Manque un ?

2022-08-19 16:25 UTC, Ayowel commented on game/tl/english/chap/chap2.rpy
> +    indigo "Most certainly. All I know are the name of this pretty things that a traveler happened to tell me once. Unfortunately, I could not associate these names to the stars."
`All I know are the names`

2022-08-19 16:25 UTC, Ayowel commented on game/tl/english/chap/chap2.rpy
> +    grosso "If you don't want to end in the dungeon, I suggest you hurry up."
`in the dungeon with me`

2022-08-19 16:25 UTC, Ayowel commented on game/tl/english/chap/chap2.rpy
> +    madame "What?! My seven crystal balls got stolen yet you do nothing??! What a bunch of incompetents! You two, and all you Guardian cat friends, you had but one job and you can't even carry it!"
`get stolen` ? Le vol est toujours en cours

2022-08-19 16:25 UTC, Ayowel commented on game/tl/english/chap/chap2.rpy
> +    indigo "Gentlemen, good evening, what might be cause of your unexpected visit?"
`to what do I owe this late and unexpected visit` ?

2022-08-19 16:25 UTC, Ayowel commented on game/tl/english/screens.rpy
> +    new "Game sound volume"
`Game volume`, ça va faire deux kilomètres dans l'interface.

2022-08-19 16:25 UTC, Ayowel commented on game/tl/english/screens.rpy
> +    new "Window Mode"
`Windowed`, il faudrait passe la version française à `Fenêtré`

2022-08-20 08:16 UTC, Lushion commented on game/tl/english/chap/chap1.rpy
> +    violet "A Guardian of Colors, you say? There are only seven of Guardian of Colors, and all of them are cats."
j'ai pas compris ce que tu veux me faire corriger :x

2022-08-20 08:18 UTC, Lushion commented on game/tl/english/screens.rpy
> +    new "Developer et sprite artist"
"et" is a lie lol

2022-08-20 08:34 UTC, Lushion commented on game/tl/english/screens.rpy
> +    new "Window Mode"
C'est le titre de la rubrique si je me trompe pas, il y a un fenpetré plus loin dans le script:
"Mode de la fenêtre"
"Fenêtré"
"Plein écran"

2022-08-20 08:37 UTC, Lushion commented on game/chap/chap2.rpy
> +    maigrichon "Eh, mais elle est passée où ta boule à toi ? T’es vraiment pas doué… L’enfant est parti par où ?"
je suis d'accord avec toi, faut voir ça avec la team d'écriture du coup!

2022-08-21 09:54 UTC, KimiNako commented on game/tl/english/chap/chap1.rpy
> +    violet "A Guardian of Colors, you say? There are only seven of Guardian of Colors, and all of them are cats."
enlever le "of"

2022-08-21 10:38 UTC, KimiNako commented on game/chap/chap2.rpy
> +    maigrichon "Eh, mais elle est passée où ta boule à toi ? T’es vraiment pas doué… L’enfant est parti par où ?"
grosso “Nous sommes à la poursuite d’un enfant ayant volé la boule du jardin de Violet, tu ne l’aurais pas vu par hasard ?“
indigo ”Les voyageurs ont bien changé… Vous n’êtes donc pas venu ici pour voir le paysage et les constellations ?”
maigrichon  “Grosso ! La boule Indigo a disparu de l’autel aussi !”
indigo “Oh non… J’ai perdu ma boule, comme c’est étrange.”
“Indigo feint l’ignorance.”
indigo “Les constellations ont détourné mon attention pendant un instant.”
maigrichon "T’es vraiment pas doué… L’enfant est parti par où ?"
grosso "Ah ! Ses traces de pas sont là, allons-y !”

2022-08-21 16:21 UTC, YoakeeAmeyuki commented on game/tl/english/chap/chap1.rpy
> +    "I snatch the ball from its paws."
"I try to snatch the ball from its paws."

2022-08-21 16:24 UTC, YoakeeAmeyuki commented on game/tl/english/chap/chap2.rpy
> +    indigo "It did not seem like it as you were running around just a few minutes ago..."
"That was not the impression you were giving off when you ran just a few minutes ago..."

2022-08-21 16:24 UTC, YoakeeAmeyuki commented on game/tl/english/chap/chap2.rpy
> +    indigo "This place is notorious for its iconic lake. All travelers who visit me are coming to admire this sublime scenery. It is naturally prohibited to take anything away from this landscape."
"This place is notorious for its iconic lake. All travelers who visit me come to admire this sublime scenery. It is naturally prohibited to take anything away from this landscape."

2022-08-21 16:26 UTC, YoakeeAmeyuki commented on game/tl/english/chap/chap2.rpy
> +    indigo "Speaking of which, it is customary to leave this place after having discovered few things, so follow me. Look! A swan right here, and ducks over there… "
"En parlant de ça, il est coutume ici de repartir de mon lac en ayant au moins découvert quelque chose, alors suis-moi. Regarde ! On peut apercevoir un cygne devant et là, des canards… "
"Speaking of which, it is customary to leave this place after having discovered at least something, so follow me. Look! A swan right here, and ducks over there… "

2022-08-21 16:26 UTC, YoakeeAmeyuki commented on game/tl/english/chap/chap2.rpy
> +    indigo "Speaking of which, it is customary to leave this place after having discovered few things, so follow me. Look! A swan right here, and ducks over there… "
"En parlant de ça, il est coutume ici de repartir de mon lac en ayant au moins découvert quelque chose, alors suis-moi. Regarde ! On peut apercevoir un cygne devant et là, des canards… "
"Speaking of which, it is customary to leave this place after having discovered at least something, so follow me. Look! A swan right here, and ducks over there… "

2022-08-21 16:27 UTC, YoakeeAmeyuki commented on game/tl/english/chap/chap2.rpy
> +    indigo "Mmmh… What use can you make out of it? In addition, as the guardian of Lake Indigo, I cannot let you outrage our venerable mistress Lady Rainbow! It is not a mere blue, it is the more nob
"Mmmh… What use can you make out of it? In addition, as the guardian of Lake Indigo, I cannot let you outrage our venerable mistress Lady Rainbow! It is not a mere blue, it is the most noble of them all: Indigo. Regarding this ball, I cannot hand it to you."

2022-08-21 16:29 UTC, YoakeeAmeyuki commented on game/tl/english/chap/chap2.rpy
> +    madame "What?! Someone is stealing my seven crystal balls and yet you do nothing??! What a bunch of incompetents! You two, and all you guardian cat friends, you had one job but you can't even car
"What?! Someone is stealing my seven crystal balls and yet you do nothing??! What a bunch of incompetents! You two, and all the guardian cat friends, you had but one job, and you can't even carry it!"

2022-08-21 16:44 UTC, merged